spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQB+S+7r1/2Et0212UJTlHtIeP6ohuLgC2HGAkGC/8jsQnI2rJQBwo9B0xe9VtHK+IZXixyP1vbuir2fRua6FI9sDOYofXBTQW/9FbDo3VJdE+BRkWBX/190e96P4FzpOHjdkoE3gs8ydCD4eUvZbZPAGNf3z+sGEwbMzU3ScaJjzeVDeKdJ64aMecU6Ads3XpnqG8fouMmx/6c5HFhkVvH49CD66GMp9Whp5kQ+bpKQK7WAZiLKlX3S2EWaoQQyKDv0G7KbTWJVJPsc4W7bd+cBVLrCAI/teI3s78tXxWOE1d8/Ppqr0jD3TObx3NnECgWkFy9pLbErgDD3qeGIEOWvdBouNcrVksLB13oYUUvIT7cZDQb0IjXxRqEEv3B0GdU='
    driver-class-name: org.h2.Driver

token:
  expiration-time: 86400000
  secret: '{cipher}AQBUzjJKcGQL2QRBWzCNJ0AXPduG8pNRO6RFJaJ+scbEIRuJRtTd5VgmAL2mTdIyMp+qyihnzqzIaijsxeP+gUocDJW5+uazA36VnzfhCPKDHrtxHQVymqxQq4zH8JhXrW0Anb+NpVta7bgcQZPWrPELyCFvzcK5DiBQLqfGfsNfpCaSouuohsw1PlZkmQDCfogrzXU33hbxayDZYNo8wTii4LdrsjNCT2tiZMAz0b+6PgJE2hQEvB6V+qdgwME2R0K6dDhF7P/nrUg6UbgWslQN/J52axsc22CFl4fY1/o05eHjdhhgDWd71C18mWfXPYs1/Np6BHfUi9vXHw3RYyj8yMjkAA2GP4FqCJRNsdePCGdF/TVzzWQn8ghjlCh5XOPStIbjq+PAnyA7bqQejOI16be769ymUbEyfA79gjqjHkMc+ndbgi9/xjCt/imYBew='

gateway:
  ip: 172.19.224.1

order-service:
  url: http://order-service/order-service/%s/orders
  exception:
    orders-is-empty: User's orders is empty.